apiVersion: ctf.ctf.io/v1alpha1
kind: ChallengeInstance
metadata:
  labels:
    app.kubernetes.io/name: chall-operator
    app.kubernetes.io/managed-by: kustomize
    ctf.io/challenge: test-web
    ctf.io/source: user-123
  name: test-web-user-123
  namespace: ctf-instances
spec:
  challengeId: "test-web"
  sourceId: "user-123"
  challengeName: "test-web"
  since: "2025-01-17T12:00:00Z"
