apiVersion: ctf.ctf.io/v1alpha1
kind: ChallengeInstance
metadata:
  labels:
    app.kubernetes.io/name: chall-operator
    app.kubernetes.io/managed-by: kustomize
  name: challengeinstance-sample
spec:
  # TODO(user): Add fields here
