apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chall-operator-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Elohyrr/k8s-chall-operator.git
    targetRevision: main
    path: config/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: chall-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
